# Generated by Django 4.2.8 on 2024-04-23 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menuapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="name",
            new_name="menu_name",
        ),
    ]
